'''
Here are defined Pipeline objects aspects
'''
FRAME = '⬜'
AVATAR = '🚶'
WALL = '🔲'
BLANK = '  '
TREE = '🌲'
SKULL = '💀'
CHEST = '📦'
ITEM_DEFAULT = '🔰'

DIALOG_UNCHECKED = '❌'
DIALOG_CHECKED = '⭕️'
DIALOG_CHECKED_DEBUG = '⭕'
DIALOG_CURSOR = '👉'
DIALOG_BUTTON = '🔳'
DIALOG_BUTTON_HOVERED = '🔲'
